# Generated by Django 3.2.13 on 2022-06-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengeluaran_barang', '0002_auto_20220607_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengeluaranbarangheader',
            old_name='TrxInNotes',
            new_name='TrxOutNotes',
        ),
        migrations.RenameField(
            model_name='pengeluaranbarangheader',
            old_name='TrxOutSuppIDf',
            new_name='TrxOutSuppIDF',
        ),
        migrations.RenameField(
            model_name='pengeluaranbarangheader',
            old_name='WhsIdf',
            new_name='WhsIDF',
        ),
    ]
