# Generated by Django 3.2.13 on 2022-06-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('WhsPK', models.AutoField(primary_key=True, serialize=False)),
                ('WhsName', models.CharField(max_length=8)),
            ],
        ),
    ]
