# Generated by Django 3.2.13 on 2022-06-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penerimaan_barang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penerimaanbarangdetail',
            options={'verbose_name_plural': 'Detail Pengeluaran Barang'},
        ),
        migrations.AlterModelOptions(
            name='penerimaanbarangheader',
            options={'verbose_name_plural': 'penerimaan barang'},
        ),
    ]
