# Generated by Django 3.2.13 on 2022-06-07 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        ('penerimaan_barang', '0002_auto_20220607_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penerimaanbarangheader',
            name='WhsIdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.warehouse', verbose_name='ID Warehouse'),
        ),
    ]
