# Generated by Django 3.2.13 on 2022-06-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penerimaan_barang', '0003_alter_penerimaanbarangheader_whsidf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penerimaanbarangheader',
            old_name='WhsIdf',
            new_name='WhsIDF',
        ),
    ]
