# Generated by Django 3.2.13 on 2022-06-07 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStok',
            fields=[
                ('ProductStokPK', models.BigAutoField(primary_key=True, serialize=False)),
                ('QtyDus', models.IntegerField(verbose_name='Quantity Dus')),
                ('QtyPcs', models.IntegerField(verbose_name='Quantity Pcs')),
                ('ProductIDF', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='ID Produk')),
                ('WarehouseIDF', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.warehouse', verbose_name='ID Warehouse')),
            ],
        ),
    ]
